### Get info about a person
GET http://localhost:3001/

### Get all persons
GET http://localhost:3001/api/persons

### Delete a person
DELETE http://localhost:3001/api/persons/2

### Post a new person
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Mussani Ruealas",
    "number": "591-73701447"
}
