### Get info about a person
GET http://localhost:3001/

### Get all persons
GET http://localhost:3001/api/persons

### Get person by id
GET http://localhost:3001/api/persons/67a0f36198abf42774824720

### Post a new person
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Mussani Ruealas",
    "number": "591-73701447"
}

### Delete a person
DELETE http://localhost:3001/api/persons/2

