### Get info about a person
GET http://localhost:3001/

### Get all persons
GET http://localhost:3001/api/persons

### Get person by id
GET http://localhost:3001/api/persons/67a23961d9ecb81b704ea00d

### Post a new person
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Mussani Ruealas",
    "number": "591-73701447"
}

### Delete a person
DELETE http://localhost:3001/api/persons/67a23961d9ecb81b704ea00d

### Put a person
PUT http://localhost:3001/api/persons/67a23961d9ecb81b704ea00d
Content-Type: application/json

{
    "name": "Juanito",
    "number": "73701447"    
}

